### ISSUE TITLE
配置环境后运行，会出现这种

### ISSUE THREAD

**Issue by learner-syh** [Kcollision/C-_Course_Design#1]
:-1: error: No rule to make target '../qcustomplot/qcustomplot.cpp', needed by 'debug/qcustomplot.o'.  Stop.

**Comment by learner-syh** [comment]
搞定了

**Comment by Kcollision** [comment]
应该要在Headers和Sources里面添加qcustomplot的.h和.cpp文件

**Comment by learner-syh** [comment]
ok,已经解决了，谢谢大佬&nbsp;


α
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月16日(星期五) 下午4:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Kcollision/Cpp_Course_Design-MyCalculator] 配置环境后运行，会出现这种 (Issue #1)





 
应该要在Headers和Sources里面添加qcustomplot的.h和.cpp文件
